Counter: counter.cpp File Reference
counter.cpp File Reference
#include <fstream>
#include <iostream>
#include <map>
#include <vector>
#include <string>
#include <algorithm>
Functions
map< char, int > counter (string fileName)
Read file and contruct map of frequencies.
void sortSecond (vector< pair< char, int > > &v)
Sort vector of pair by second value in-place.
void printV (const vector< pair< char, int > > &v)
Print vector of pairs.
int main ()
Function Documentation
map<char, int> counter (string fileName)
Read file and contruct map of frequencies.
Keys are unique symbols, values are number of occurences.
Parameters
[in] fileName The name of file to read from
Returns
map of symbol/occurences
Definition at line 23 of file counter.cpp.
Referenced by main().
 {
     char x;
     map<char, int> frequencies;
     ifstream inFile;
     inFile.open(fileName);
     while (inFile >> x)
     {
         frequencies[x]++;
     }
     inFile.close();
     return frequencies;
 }
int main ()
Definition at line 69 of file counter.cpp.
References counter(), printV(), and sortSecond().
 {
     map<char, int> freqs = counter("input.txt");
     vector< pair<char, int> > freqs_vec(freqs.begin(), freqs.end());
     sortSecond(freqs_vec);
     printV(freqs_vec);
     return 0;
 }
void printV (const vector< pair< char, int > > & v)
Print vector of pairs.
Parameters
[in] v vector of pairs
Definition at line 62 of file counter.cpp.
Referenced by main().
{
     for_each(v.begin(), v.end(), [](pair<char, int> x)
     {
         cout << x.first << " was found " << x.second << " times." << endl;
     });
 }
void sortSecond (vector< pair< char, int > > & v)
Sort vector of pair by second value in-place.
Parameters
v vector of pairs
Definition at line 46 of file counter.cpp.
Referenced by main().
{
     auto sortingFunc = [](pair<char, int> x, pair<char, int> y)
     {
         return x.second > y.second;
     };
     sort(v.begin(), v.end(), sortingFunc);
 }